name:               "Stratosphere | Above the Clouds"
markdown:           redcarpet
pygments:           true
timezone:           "Europe/Berlin"
safe:               true
lsi:                false

# pagination
paginate:           10
paginate_path:      "news/page-:num"

# see https://github.com/mojombo/jekyll/issues/332
baseurl:            /ozone

